const AUTH_ENDPOINT = window.KAYAKOMAT_AUTH_ENDPOINT || 'https://923vmokr87.execute-api.eu-central-1.amazonaws.com/production/authorization';
const BOOKINGS_ENDPOINT = window.KAYAKOMAT_BOOKINGS_ENDPOINT || 'https://923vmokr87.execute-api.eu-central-1.amazonaws.com/production/admin/bookings';
const demoBookings = [
  {id:'KB-20481',guest:'Maja Andersson',email:'maja@example.com',location:'Stockholm · Hammarby',start:'2026-08-15T09:30',equipment:'2 × Kayak',status:'Active',total:640},
  {id:'KB-20482',guest:'Oliver Berg',email:'oliver@example.com',location:'Stockholm · Hammarby',start:'2026-08-15T11:00',equipment:'1 × Double kayak',status:'Confirmed',total:420},
  {id:'KB-20477',guest:'Freja Lind',email:'freja@example.com',location:'Göteborg · Långedrag',start:'2026-08-15T10:15',equipment:'2 × SUP',status:'Active',total:520},
  {id:'KB-20464',guest:'Liam Nilsson',email:'liam@example.com',location:'Malmö · Ribersborg',start:'2026-08-14T14:00',equipment:'1 × Kayak',status:'Completed',total:310},
  {id:'KB-20448',guest:'Astrid Holm',email:'astrid@example.com',location:'Göteborg · Långedrag',start:'2026-08-20T13:30',equipment:'4 × Kayak',status:'Confirmed',total:1280},
  {id:'KB-20421',guest:'Noah Eriksson',email:'noah@example.com',location:'Malmö · Ribersborg',start:'2026-08-22T09:00',equipment:'2 × Kayak',status:'Cancelled',total:0}
];
let bookings=[]; let usingDemo=false; let currentPage=1; let hasNextPage=true;
const $=id=>document.getElementById(id);
function currency(amount){return new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',maximumFractionDigits:0}).format(amount)}
function formatDate(value){return new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value))}
function query(){return {search:$('search').value.trim().toLowerCase(),location:$('location').value,status:$('status').value,from:$('from-date').value,to:$('to-date').value}}
function filtered(){const f=query();return bookings.filter(b=>!f.search||[b.id,b.guest,b.email].join(' ').toLowerCase().includes(f.search)).filter(b=>!f.location||b.location===f.location).filter(b=>!f.status||b.status===f.status).filter(b=>!f.from||b.start.slice(0,10)>=f.from).filter(b=>!f.to||b.start.slice(0,10)<=f.to)}
function render(){const rows=filtered();$('result-count').textContent=`${rows.length} booking${rows.length===1?'':'s'} found`;$('booking-list').innerHTML=rows.map(b=>`<tr><td><span class="booking-id">${b.id}</span></td><td>${b.guest}<small>${b.email}</small></td><td>${b.location}</td><td>${formatDate(b.start)}</td><td>${b.equipment}</td><td><span class="badge ${b.status.toLowerCase()}">${b.status}</span></td><td>${currency(b.total)}</td></tr>`).join('');$('empty-state').hidden=rows.length>0;$('page-label').textContent=`Page ${currentPage}`;$('previous-page').disabled=currentPage===1;$('next-page').disabled=!hasNextPage}
function populateLocations(){const current=$('location').value;const locations=[...new Set(bookings.map(b=>b.location))];$('location').innerHTML='<option value="">All locations</option>'+locations.map(l=>`<option>${l}</option>`).join('');$('location').value=current}
function summary(){const today='2026-08-15';$('today-count').textContent=bookings.filter(b=>b.start.startsWith(today)).length;$('active-count').textContent=bookings.filter(b=>b.status==='Active').length;$('revenue').textContent=currency(bookings.filter(b=>b.status==='Confirmed').reduce((sum,b)=>sum+b.total,0))}
function normaliseBooking(item){const guest=item.guest||item.customer||{};const start=item.start||item.startTime||item.start_date||item.bookingStart||'';return {id:item.id||item.bookingId||item.reference||'—',guest:item.guestName||guest.name||[guest.firstName,guest.lastName].filter(Boolean).join(' ')||'Unknown guest',email:item.email||guest.email||'—',location:item.locationName||item.location?.name||item.location||'—',start,equipment:item.equipmentName||item.equipment||item.items?.map(x=>`${x.quantity||1} × ${x.name}`).join(', ')||'—',status:item.status||'Confirmed',total:Number(item.total||item.totalAmount||item.price||0)}}
async function loadBookings(){ $('result-count').textContent='Loading bookings…';try{const url=new URL(BOOKINGS_ENDPOINT);url.searchParams.set('page',currentPage);const startTime=$('from-date').value;if(startTime)url.searchParams.set('startTime',startTime);const response=await fetch(url,{headers:{Authorization:localStorage.kayakomatToken||''}});if(!response.ok)throw new Error('Request failed');let data=await response.json();if(typeof data.body==='string')data={...data,body:JSON.parse(data.body)};const payload=data.body&&typeof data.body==='object'?data.body:data;const raw=Array.isArray(payload)?payload:payload.bookings||payload.items||payload.data||[];bookings=raw.map(normaliseBooking);hasNextPage=Boolean(payload.hasNextPage||payload.nextPage||payload.pagination?.hasNextPage||payload.pagination?.nextPage)||bookings.length>0;usingDemo=false;$('api-note').textContent='Live API';}catch(error){bookings=demoBookings;hasNextPage=false;usingDemo=true;$('api-note').textContent='Demo data · API unavailable'}populateLocations();summary();render()}
async function login(event){event.preventDefault();const email=$('email').value,password=$('password').value;$('login-error').hidden=true;const submit=event.submitter;submit.disabled=true;submit.textContent='Signing in…';try{const response=await fetch(AUTH_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||data.error||'Your email or password was not accepted.');const token=data.token||data.accessToken||data.access_token||data.idToken||data.id_token;if(!token)throw new Error('The authorization response did not contain an access token.');localStorage.kayakomatToken=token;showApp()}catch(error){$('login-error').textContent=error.message||'Unable to sign in. Please try again.';$('login-error').hidden=false}finally{submit.disabled=false;submit.innerHTML='Sign in <span>→</span>'}}
function showApp(){$('login-view').hidden=true;$('app-view').hidden=false;loadBookings()}
$('login-form').addEventListener('submit',login);['search','location','status','to-date'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));$('from-date').addEventListener('change',()=>{currentPage=1;loadBookings()});$('clear-filters').onclick=()=>{['search','location','status','from-date','to-date'].forEach(id=>$(id).value='');currentPage=1;loadBookings()};$('refresh').onclick=loadBookings;$('previous-page').onclick=()=>{if(currentPage>1){currentPage--;loadBookings()}};$('next-page').onclick=()=>{if(hasNextPage){currentPage++;loadBookings()}};$('logout').onclick=()=>{localStorage.removeItem('kayakomatToken');$('app-view').hidden=true;$('login-view').hidden=false};if(localStorage.kayakomatToken&&localStorage.kayakomatToken!=='demo-session')showApp();
